package de.htwsaar.peopl.core.tests.basics;

/*Generated by MPS */

import junit.framework.TestCase;
import junit.framework.Assert;

public class FooTest_Test extends TestCase {
  public void test_testFoo() throws Exception {
    Assert.assertEquals(10, 20 - 10);
    Assert.assertNull(new Object());
  }
}
