package de.htwsaar.peopl.core.tests.basics;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;

@MPSLaunch
public class TypeHello_Test_Test extends BaseTransformationTest {
  @Test
  public void test_TypeHello_Test() throws Throwable {
    initTest("${mps.home}", "r:c5ff0be2-390d-4569-a3a9-b853483d94d1(de.htwsaar.peopl.core.tests.basics@tests)");
    runTest("de.htwsaar.peopl.core.tests.basics.TypeHello_Test_Test$TestBody", "testMethod", false);
  }

  @MPSLaunch
  public static class TestBody extends BaseEditorTestBody {
    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("4568368941932553701", "4568368941932548310");
      typeString("2");
    }
  }
}
