package client;

/*Generated by MPS */

import common.TextMessage;

/**
 * Listener that gets informed every time when the chat client receives a new
 * message
 */
public interface ChatLineListener {
  /**
   * New text message received by client.
   * 
   * @param line
   *            the new message
   */
  public void newChatLine(TextMessage msg);
}
