package common;

/*Generated by MPS */

import client.ChatLineListener;

public interface ChatComponent {
  public String getName();
  public void addLineListener(ChatLineListener listener);
  public void removeLineListener(ChatLineListener listner);
  public void fireAddLine(TextMessage msg);
}
